export const HomeObjOne = {
  id: 'news',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Ajankohtaista ja uutisia',
  headline: 'Uutta webbisivuleiskaa',
  description: "Uusi ja hieno webbisivuleiska testissä tässä näin.",
  buttonLabel: 'Lue lisää...',
  imgStart: false,
  img: require('../../assets/images/beer.png'),
  alt: 'Beer',
  dark: true,
  primary: true,
  darkText: false,
}

export const HomeObjTwo = {
  id: 'products',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Oluita ja vielä kerran oluita',
  headline: 'HANASTA, PULLOSTA SEKÄ TÖLKISTÄ',
  description: "Hanasta löytyy ja vähän muualtakin...",
  buttonLabel: 'Tutustu tuotteisiin...',
  imgStart: true,
  img: require('../../assets/images/beer.png'),
  alt: 'Beer',
  dark: false,
  primary: false,
  darkText: true,
}

export const HomeObjThree = {
  id: 'story',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: '',
  headline: 'Olipa kerran...',
  description: "...ja sen pituinen se.",
  buttonLabel: 'Mitäs täältä löytyy...',
  imgStart: false,
  img: require('../../assets/images/beer.png'),
  alt: 'Beer',
  dark: true,
  primary: true,
  darkText: false,
}